version: '3.8'

services:
  backend:
    build: ./backend
    container_name: iris_backend
    ports:
      - "5000:5000"
    networks:
      - iris-net

  frontend:
    build: ./frontend
    container_name: iris_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - iris-net

networks:
  iris-net:
    driver: bridge
